// This file was generated by TypeORM, and assumes you have installed the following:
// npm install --save-dev typeorm dotenv
import "dotenv/config";
import { defineConfig } from "typeorm/config";

export default defineConfig({
  schema: "typeorm/schema.typeorm",
  migrations: {
    path: "typeorm/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
